services:
  jekyll:
    image: jekyll/jekyll:4.2.0
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle/:/usr/local/bundle
    ports:
      - "4000:4000"
    command: jekyll serve --force_polling --drafts